/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbprzychodnia;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class FrmDoctors extends javax.swing.JFrame {

    Connection cn = new Connection();        
    DefaultTableModel lista = new DefaultTableModel();
    
    //obsluga tabeli 
    public void TableDoctors() {
        
        if(!"".equals(txtWyszukajLek.getText())) {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT * FROM lekarze "
                    + "WHERE UPPER(imie) "
                    + "LIKE '%" + txtWyszukajLek.getText().toUpperCase() + "%' " 
                    + " OR UPPER(nazwisko) "
                    + "LIKE '%" + txtWyszukajLek.getText().toUpperCase() + "%' "
                    + " OR id_lekarza "
                    + "LIKE '%" + txtWyszukajLek.getText() + "%' "
                    + " ORDER BY nazwisko";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID");
            lista.addColumn("Imie");
            lista.addColumn("Nazwisko");
            lista.addColumn("Telefon");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_lekarza"), cn.rs.getString("imie"), 
                        cn.rs.getString("nazwisko"), cn.rs.getString("telefon")});
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaLek.setModel(lista);            
        } else {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT * FROM lekarze ORDER BY nazwisko";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID");
            lista.addColumn("Imie");
            lista.addColumn("Nazwisko");
            lista.addColumn("Telefon");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_lekarza"), cn.rs.getString("imie"), 
                        cn.rs.getString("nazwisko"), cn.rs.getString("telefon")});
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaLek.setModel(lista);
        }
    }
    
    //wybranie pola poprzez klikniecie i uzupelnienie pustych pol formularza
    public void Selection() {
        
        int column = tabelaLek.getSelectedRow();
        
        txtIDLek.setText(tabelaLek.getValueAt(column, 0).toString());
        txtImieLek.setText(tabelaLek.getValueAt(column, 1).toString());
        txtNazwiskoLek.setText(tabelaLek.getValueAt(column, 2).toString());
        txtTelefonLek.setText(tabelaLek.getValueAt(column, 3).toString());
        
    }
    
    public FrmDoctors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtWyszukajLek = new javax.swing.JTextField();
        btnDodajLekarzaLek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDLek = new javax.swing.JTextField();
        txtImieLek = new javax.swing.JTextField();
        txtNazwiskoLek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonLek = new javax.swing.JTextField();
        btnZapiszImieLek = new javax.swing.JButton();
        btnZapiszNazwiskoLek = new javax.swing.JButton();
        btnZapiszTelefonLek = new javax.swing.JButton();
        btnEdytujImieLek = new javax.swing.JButton();
        btnEdytujNazwiskoLek = new javax.swing.JButton();
        btnEdytujTelefonLek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLek = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnOKLekarze = new javax.swing.JButton();
        btnUsunLekarzaLek = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LEKARZE");

        txtWyszukajLek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWyszukajLekMouseClicked(evt);
            }
        });
        txtWyszukajLek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWyszukajLekKeyReleased(evt);
            }
        });

        btnDodajLekarzaLek.setText("Dodaj lekarza");
        btnDodajLekarzaLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajLekarzaLekActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Imię");

        jLabel4.setText("Nazwisko");

        txtIDLek.setEnabled(false);

        txtImieLek.setEnabled(false);

        txtNazwiskoLek.setEnabled(false);

        jLabel5.setText("Telefon");

        txtTelefonLek.setEnabled(false);

        btnZapiszImieLek.setText("Zapisz");
        btnZapiszImieLek.setEnabled(false);
        btnZapiszImieLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszImieLekActionPerformed(evt);
            }
        });

        btnZapiszNazwiskoLek.setText("Zapisz");
        btnZapiszNazwiskoLek.setEnabled(false);
        btnZapiszNazwiskoLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszNazwiskoLekActionPerformed(evt);
            }
        });

        btnZapiszTelefonLek.setText("Zapisz");
        btnZapiszTelefonLek.setEnabled(false);
        btnZapiszTelefonLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszTelefonLekActionPerformed(evt);
            }
        });

        btnEdytujImieLek.setText("Edytuj");
        btnEdytujImieLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdytujImieLekActionPerformed(evt);
            }
        });

        btnEdytujNazwiskoLek.setText("Edytuj");
        btnEdytujNazwiskoLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdytujNazwiskoLekActionPerformed(evt);
            }
        });

        btnEdytujTelefonLek.setText("Edytuj");
        btnEdytujTelefonLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdytujTelefonLekActionPerformed(evt);
            }
        });

        tabelaLek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaLek.setCellSelectionEnabled(true);
        tabelaLek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLekMouseClicked(evt);
            }
        });
        tabelaLek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaLekKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLek);

        jLabel6.setText("Wyszukaj");

        btnOKLekarze.setText("OK");
        btnOKLekarze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKLekarzeActionPerformed(evt);
            }
        });

        btnUsunLekarzaLek.setText("Usuń lekarza");
        btnUsunLekarzaLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunLekarzaLekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOKLekarze, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtImieLek)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdytujImieLek)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnZapiszImieLek))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelefonLek)
                                            .addComponent(txtNazwiskoLek))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEdytujTelefonLek)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnZapiszTelefonLek))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnEdytujNazwiskoLek)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnZapiszNazwiskoLek))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtWyszukajLek)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDodajLekarzaLek, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIDLek, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUsunLekarzaLek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(3, 3, 3)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWyszukajLek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajLekarzaLek)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDLek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsunLekarzaLek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtImieLek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZapiszImieLek)
                    .addComponent(btnEdytujImieLek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNazwiskoLek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZapiszNazwiskoLek)
                    .addComponent(btnEdytujNazwiskoLek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefonLek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZapiszTelefonLek)
                    .addComponent(btnEdytujTelefonLek))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOKLekarze)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajLekarzaLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajLekarzaLekActionPerformed
        
        FrmAddDoctor form = new FrmAddDoctor(); 
        
        form.setVisible(true);
    }//GEN-LAST:event_btnDodajLekarzaLekActionPerformed

    private void txtWyszukajLekKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWyszukajLekKeyReleased
        
        TableDoctors();
    }//GEN-LAST:event_txtWyszukajLekKeyReleased

    private void tabelaLekKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaLekKeyReleased
        
        Selection();
    }//GEN-LAST:event_tabelaLekKeyReleased

    private void tabelaLekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLekMouseClicked
        
        Selection();
    }//GEN-LAST:event_tabelaLekMouseClicked

    private void btnZapiszImieLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszImieLekActionPerformed
        
        cn.connect();
        String sql = "UPDATE lekarze "
                + "SET imie = '" + txtImieLek.getText()
                + "'WHERE id_lekarza = " + Integer.parseInt(txtIDLek.getText());
        cn.executeUpdating(sql);
        cn.disconnect();
        txtImieLek.setEnabled(false);
        btnEdytujImieLek.setEnabled(true);
        btnZapiszImieLek.setEnabled(false);
        TableDoctors();
    }//GEN-LAST:event_btnZapiszImieLekActionPerformed

    private void btnEdytujImieLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdytujImieLekActionPerformed
        
        txtImieLek.setEnabled(true);
        btnZapiszImieLek.setEnabled(true);
        btnEdytujImieLek.setEnabled(false);
    }//GEN-LAST:event_btnEdytujImieLekActionPerformed

    private void btnZapiszNazwiskoLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszNazwiskoLekActionPerformed
        
        cn.connect();
        String sql = "UPDATE lekarze "
                + "SET nazwisko = '" + txtNazwiskoLek.getText()
                + "'WHERE id_lekarza = " + Integer.parseInt(txtIDLek.getText());
        cn.executeUpdating(sql);
        cn.disconnect();
        txtNazwiskoLek.setEnabled(false);
        btnEdytujNazwiskoLek.setEnabled(true);
        btnZapiszNazwiskoLek.setEnabled(false);
        TableDoctors();
    }//GEN-LAST:event_btnZapiszNazwiskoLekActionPerformed

    private void btnEdytujNazwiskoLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdytujNazwiskoLekActionPerformed
        
        txtNazwiskoLek.setEnabled(true);
        btnZapiszNazwiskoLek.setEnabled(true);
        btnEdytujNazwiskoLek.setEnabled(false);
    }//GEN-LAST:event_btnEdytujNazwiskoLekActionPerformed

    private void btnZapiszTelefonLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszTelefonLekActionPerformed
        
        cn.connect();
        String sql = "UPDATE lekarze "
                + "SET telefon = '" + txtTelefonLek.getText()
                + "'WHERE id_lekarza = " + Integer.parseInt(txtIDLek.getText());
        cn.executeUpdating(sql);
        cn.disconnect();
        txtTelefonLek.setEnabled(false);
        btnEdytujTelefonLek.setEnabled(true);
        btnZapiszTelefonLek.setEnabled(false);
        TableDoctors();
    }//GEN-LAST:event_btnZapiszTelefonLekActionPerformed

    private void btnEdytujTelefonLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdytujTelefonLekActionPerformed
        
        txtTelefonLek.setEnabled(true);
        btnZapiszTelefonLek.setEnabled(true);
        btnEdytujTelefonLek.setEnabled(false);
    }//GEN-LAST:event_btnEdytujTelefonLekActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.setTitle("Lekarze");
    }//GEN-LAST:event_formWindowOpened

    private void txtWyszukajLekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWyszukajLekMouseClicked
        
        TableDoctors();
    }//GEN-LAST:event_txtWyszukajLekMouseClicked

    private void btnOKLekarzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKLekarzeActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOKLekarzeActionPerformed

    private void btnUsunLekarzaLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunLekarzaLekActionPerformed
        
        if(!"".equals(txtIDLek.getText())) {
            cn.connect();
            String sql = "SELECT * FROM lekarze "
                    + "WHERE id_lekarza = " + Integer.parseInt(txtIDLek.getText());
            cn.executeQuerying(sql);
            int resp = JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz wykonać "
                    + sql + "?");

            if(resp == JOptionPane.YES_OPTION) {
                sql = "DELETE FROM lekarze "
                        + " WHERE id_lekarza = " + Integer.parseInt(txtIDLek.getText());
                cn.executeUpdating(sql);
                cn.disconnect();
                txtIDLek.setText("");
                txtImieLek.setText("");
                txtNazwiskoLek.setText("");
                txtTelefonLek.setText("");
                TableDoctors();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Najpierw wybierz lekarza.");
        }
    }//GEN-LAST:event_btnUsunLekarzaLekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDoctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajLekarzaLek;
    private javax.swing.JButton btnEdytujImieLek;
    private javax.swing.JButton btnEdytujNazwiskoLek;
    private javax.swing.JButton btnEdytujTelefonLek;
    private javax.swing.JButton btnOKLekarze;
    private javax.swing.JButton btnUsunLekarzaLek;
    private javax.swing.JButton btnZapiszImieLek;
    private javax.swing.JButton btnZapiszNazwiskoLek;
    private javax.swing.JButton btnZapiszTelefonLek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLek;
    private javax.swing.JTextField txtIDLek;
    private javax.swing.JTextField txtImieLek;
    private javax.swing.JTextField txtNazwiskoLek;
    private javax.swing.JTextField txtTelefonLek;
    private javax.swing.JTextField txtWyszukajLek;
    // End of variables declaration//GEN-END:variables
}
