/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbprzychodnia;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class FrmMedicines extends javax.swing.JFrame {

    Connection cn = new Connection();        
    DefaultTableModel lista = new DefaultTableModel();
    
    //wypelnienie tabeli
    public void TableMedicines() {
        
        if(!"".equals(txtWyszukajLekarstwo.getText())) {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT * FROM lekarstwa "
                    + "WHERE UPPER(nazwa_lekarstwa) "
                    + "LIKE '%" + txtWyszukajLekarstwo.getText().toUpperCase() + "%' " 
                    + " OR UPPER(sklad) "
                    + "LIKE '%" + txtWyszukajLekarstwo.getText().toUpperCase() + "%' "
                    + " ORDER BY nazwa_lekarstwa";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID");
            lista.addColumn("Nazwa");
            lista.addColumn("Skład");
            lista.addColumn("Przeciwwskazania");
            lista.addColumn("Skutki uboczne");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_lekarstwa"), cn.rs.getString("nazwa_lekarstwa"), 
                        cn.rs.getString("sklad"), cn.rs.getString("przeciwwskazania"), cn.rs.getString("skutki_uboczne")});
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaLekarstw.setModel(lista);            
        } else {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT * FROM lekarstwa ORDER BY nazwa_lekarstwa";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID");
            lista.addColumn("Nazwa");
            lista.addColumn("Skład");
            lista.addColumn("Przeciwwskazania");
            lista.addColumn("Skutki uboczne");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_lekarstwa"), cn.rs.getString("nazwa_lekarstwa"), 
                        cn.rs.getString("sklad"), cn.rs.getString("przeciwwskazania"), cn.rs.getString("skutki_uboczne")});
                }
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaLekarstw.setModel(lista); 
        }
    }
    
    //uzupelnienie pol formularza poprzez klikniecie danego wiersza tabeli
    public void Selection() {
        
        int row = tabelaLekarstw.getSelectedRow();
        
        txtIDLekarstwa.setText(tabelaLekarstw.getValueAt(row, 0).toString());
        txtNazwaLekarstwa.setText(tabelaLekarstw.getValueAt(row, 1).toString());
        txtSkladLekarstwa.setText(tabelaLekarstw.getValueAt(row, 2).toString());
        txtPrzeciwwskazaniaLekarstwa.setText(tabelaLekarstw.getValueAt(row, 3).toString());   
        txtSkutkiUboczneLekarstwa.setText(tabelaLekarstw.getValueAt(row, 4).toString());
    }
    
    public FrmMedicines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtWyszukajLekarstwo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDLekarstwa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLekarstw = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSkladLekarstwa = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrzeciwwskazaniaLekarstwa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtNazwaLekarstwa = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSkutkiUboczneLekarstwa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnOKLekarstwa = new javax.swing.JButton();
        btnDrukujUlotkeLekarstwa = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KATALOG LEKARSTW");

        txtWyszukajLekarstwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWyszukajLekarstwoMouseClicked(evt);
            }
        });
        txtWyszukajLekarstwo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWyszukajLekarstwoKeyReleased(evt);
            }
        });

        jLabel3.setText("ID lekarstwa");

        jLabel4.setText("Skład");

        tabelaLekarstw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaLekarstw.setCellSelectionEnabled(true);
        tabelaLekarstw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLekarstwMouseClicked(evt);
            }
        });
        tabelaLekarstw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaLekarstwKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLekarstw);

        jLabel6.setText("Wyszukaj");

        jScrollPane2.setEnabled(false);

        txtSkladLekarstwa.setColumns(20);
        txtSkladLekarstwa.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtSkladLekarstwa.setLineWrap(true);
        txtSkladLekarstwa.setRows(5);
        txtSkladLekarstwa.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtSkladLekarstwa);

        jLabel7.setText("Przeciwwskazania");

        jScrollPane3.setEnabled(false);

        txtPrzeciwwskazaniaLekarstwa.setColumns(20);
        txtPrzeciwwskazaniaLekarstwa.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtPrzeciwwskazaniaLekarstwa.setLineWrap(true);
        txtPrzeciwwskazaniaLekarstwa.setRows(5);
        txtPrzeciwwskazaniaLekarstwa.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtPrzeciwwskazaniaLekarstwa);

        jLabel2.setText("Nazwa");

        txtSkutkiUboczneLekarstwa.setColumns(20);
        txtSkutkiUboczneLekarstwa.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtSkutkiUboczneLekarstwa.setLineWrap(true);
        txtSkutkiUboczneLekarstwa.setRows(5);
        txtSkutkiUboczneLekarstwa.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtSkutkiUboczneLekarstwa);

        jLabel5.setText("Skutki uboczne");

        btnOKLekarstwa.setText("OK");
        btnOKLekarstwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKLekarstwaActionPerformed(evt);
            }
        });

        btnDrukujUlotkeLekarstwa.setText("Drukuj ulotkę");
        btnDrukujUlotkeLekarstwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrukujUlotkeLekarstwaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(txtWyszukajLekarstwo)
                                    .addComponent(jScrollPane2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtIDLekarstwa, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNazwaLekarstwa, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnDrukujUlotkeLekarstwa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOKLekarstwa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWyszukajLekarstwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDLekarstwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazwaLekarstwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKLekarstwa)
                    .addComponent(btnDrukujUlotkeLekarstwa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWyszukajLekarstwoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWyszukajLekarstwoKeyReleased
        
        TableMedicines();
    }//GEN-LAST:event_txtWyszukajLekarstwoKeyReleased

    private void tabelaLekarstwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaLekarstwKeyReleased
        
        Selection();
    }//GEN-LAST:event_tabelaLekarstwKeyReleased

    private void tabelaLekarstwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLekarstwMouseClicked
        
        Selection();
    }//GEN-LAST:event_tabelaLekarstwMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.setTitle("Katalog lekarstw");
    }//GEN-LAST:event_formWindowOpened

    private void txtWyszukajLekarstwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWyszukajLekarstwoMouseClicked
        TableMedicines();
    }//GEN-LAST:event_txtWyszukajLekarstwoMouseClicked

    private void btnOKLekarstwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKLekarstwaActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOKLekarstwaActionPerformed

    private void btnDrukujUlotkeLekarstwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrukujUlotkeLekarstwaActionPerformed
        
        com.itextpdf.text.Font f1 = null;
        com.itextpdf.text.Font f2 = null;
        com.itextpdf.text.Font f3 = null;
        try {
            BaseFont bf = BaseFont.createFont(BaseFont.TIMES_ROMAN, BaseFont.CP1250, BaseFont.EMBEDDED);
            f1 = new com.itextpdf.text.Font(bf, 18, Font.BOLD, BaseColor.BLACK);
            f2 = new com.itextpdf.text.Font(bf, 14, Font.PLAIN, BaseColor.BLACK);
            f3 = new com.itextpdf.text.Font(bf, 12, Font.PLAIN, BaseColor.DARK_GRAY);
        } catch (DocumentException ex) {
            Logger.getLogger(FrmVisits.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmVisits.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(!"".equals(txtIDLekarstwa.getText()) && !"".equals(txtNazwaLekarstwa.getText()) 
            && !"".equals(txtSkladLekarstwa.getText()) && !"".equals(txtPrzeciwwskazaniaLekarstwa.getText()) 
            && !"".equals(txtSkutkiUboczneLekarstwa.getText())) {

            String RESULT = "Ulotka.pdf";            

            Document document = new Document();

            try {               
                PdfWriter.getInstance(document, new FileOutputStream(RESULT));        
                document.open();
                String txt = "Ulotka - " + txtNazwaLekarstwa.getText() + " ";
                document.add(new Paragraph(txt, f1));        
                document.add(new Paragraph("-------------------------------------"
                        + "-----------------------------------------------------"
                        + "----------------------------------------", f3));
               
                document.add(new Paragraph("\n------- Sklad", f2));                
                txt = ""+txtSkladLekarstwa.getText()+"";
                document.add(new Paragraph(txt, f3));        
                
                document.add(new Paragraph("\n------- Przeciwwskazania", f2));
                txt = ""+txtPrzeciwwskazaniaLekarstwa.getText()+"";
                document.add(new Paragraph(txt, f3));        
                
                document.add(new Paragraph("\n------- Skutki uboczne", f2));                
                txt = ""+txtSkutkiUboczneLekarstwa.getText()+"";
                document.add(new Paragraph(txt, f3));                    
                
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("-------------------------------------"
                        + "-----------------------------------------------------"
                        + "----------------------------------------", f3));

                document.close();
                
            } catch (DocumentException ex) {
                JOptionPane.showMessageDialog(null, "Błąd pliku. " + ex);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Plik nie został odnaleziony. Sprawdź ścieżkę pliku. " + ex);
            }

            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File("D:/INFORMATICS/Projects Java/DBPrzychodnia2/Ulotka.pdf");
                    Desktop.getDesktop().open(myFile);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Błąd podczas uruchamiania pliku. Sprawdź ścieżkę pliku." + ex);
                }
            }
        }
    }//GEN-LAST:event_btnDrukujUlotkeLekarstwaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMedicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrukujUlotkeLekarstwa;
    private javax.swing.JButton btnOKLekarstwa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelaLekarstw;
    private javax.swing.JTextField txtIDLekarstwa;
    private javax.swing.JTextField txtNazwaLekarstwa;
    private javax.swing.JTextArea txtPrzeciwwskazaniaLekarstwa;
    private javax.swing.JTextArea txtSkladLekarstwa;
    private javax.swing.JTextArea txtSkutkiUboczneLekarstwa;
    private javax.swing.JTextField txtWyszukajLekarstwo;
    // End of variables declaration//GEN-END:variables
}
