/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbprzychodnia;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class FrmSearchVisit extends javax.swing.JFrame {

    Connection cn = new Connection();        
    DefaultTableModel lista = new DefaultTableModel();
    
    //wyswietlanie zawartosci tabeli
    public void TableVisits() {
        
        if(!"".equals(txtWyszukajWiz.getText())) {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT wizyty.id_wizyty, wizyty.data_wizyty, wizyty.nr_ubezpieczenia, "
                    + "pacjenci.imie, pacjenci.nazwisko, wizyty.objawy" 
                    + " FROM wizyty, pacjenci" 
                    + " WHERE wizyty.nr_ubezpieczenia=pacjenci.nr_ubezpieczenia and (wizyty.nr_ubezpieczenia" 
                    + " LIKE '%" + txtWyszukajWiz.getText() + "%' "
                    + " OR (UPPER(pacjenci.imie)"
                    + " LIKE '%" + txtWyszukajWiz.getText().toUpperCase() + "%')"
                    + " OR (UPPER(pacjenci.nazwisko)"
                    + " LIKE '%" + txtWyszukajWiz.getText().toUpperCase() +"%')"
                    + " OR (wizyty.data_wizyty LIKE '" + txtWyszukajWiz.getText() + "%'))"
                    + " ORDER BY wizyty.data_wizyty";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID wizyty");
            lista.addColumn("Data");
            lista.addColumn("Nr ubezp.");
            lista.addColumn("Imie");
            lista.addColumn("Nazwisko");
            lista.addColumn("Objawy");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_wizyty"), cn.rs.getString("data_wizyty"),
                        cn.rs.getString("nr_ubezpieczenia"), cn.rs.getString("imie"), cn.rs.getString("nazwisko"), 
                        cn.rs.getString("objawy")});
                }
            } catch (SQLException ex) {                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaWiz.setModel(lista);            
        } else {
            lista.setColumnCount(0);
            lista.setRowCount(0);
            cn.connect();
            String sql = "SELECT wizyty.id_wizyty, wizyty.data_wizyty, wizyty.nr_ubezpieczenia,"
                    + " pacjenci.imie, pacjenci.nazwisko, wizyty.objawy" 
                    + " FROM wizyty, pacjenci"
                    + " WHERE wizyty.nr_ubezpieczenia=pacjenci.nr_ubezpieczenia"
                    + " ORDER BY wizyty.data_wizyty";
            
            cn.executeQuerying(sql);
            
            lista.addColumn("ID wizyty");
            lista.addColumn("Data");
            lista.addColumn("Nr ubezp.");
            lista.addColumn("Imie");
            lista.addColumn("Nazwisko");
            lista.addColumn("Objawy");
            try {
                while (cn.rs.next()) {
                    
                    lista.addRow(new String[]{cn.rs.getString("id_wizyty"), cn.rs.getString("data_wizyty"),
                        cn.rs.getString("nr_ubezpieczenia"), cn.rs.getString("imie"), cn.rs.getString("nazwisko"), 
                        cn.rs.getString("objawy")});
                }
            } catch (SQLException ex) {                
                JOptionPane.showMessageDialog(null, "Błąd podczas przeglądania bazy danych: " + ex);
            }
            cn.disconnect();
            tabelaWiz.setModel(lista);
        }
    }
    
    //uzupelnie pola po wybraniu wiersza z tabeli
    public void Selection() {
        
        int row = tabelaWiz.getSelectedRow();        
        txtIDWiz.setText(tabelaWiz.getValueAt(row, 0).toString());        
    }
    
    
    public FrmSearchVisit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtWyszukajWiz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIDWiz = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaWiz = new javax.swing.JTable();
        btnOKWizyty = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ARCHIWUM WIZYT");

        jLabel2.setText("Wyszukaj");

        txtWyszukajWiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWyszukajWizMouseClicked(evt);
            }
        });
        txtWyszukajWiz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWyszukajWizKeyReleased(evt);
            }
        });

        jLabel3.setText("ID");

        txtIDWiz.setEnabled(false);

        tabelaWiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaWiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaWizMouseClicked(evt);
            }
        });
        tabelaWiz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaWizKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaWiz);

        btnOKWizyty.setText("OK");
        btnOKWizyty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKWizytyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 196, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 196, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWyszukajWiz)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIDWiz, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOKWizyty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWyszukajWiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDWiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOKWizyty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWyszukajWizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWyszukajWizMouseClicked
        
        TableVisits();
    }//GEN-LAST:event_txtWyszukajWizMouseClicked

    private void txtWyszukajWizKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWyszukajWizKeyReleased
        
        TableVisits();
    }//GEN-LAST:event_txtWyszukajWizKeyReleased

    private void tabelaWizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaWizMouseClicked
        
        Selection();
    }//GEN-LAST:event_tabelaWizMouseClicked

    private void tabelaWizKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaWizKeyReleased
        
        Selection();
    }//GEN-LAST:event_tabelaWizKeyReleased

    private void btnOKWizytyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKWizytyActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOKWizytyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        this.setTitle("Archiwum wizyt");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSearchVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSearchVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSearchVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSearchVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSearchVisit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOKWizyty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaWiz;
    private javax.swing.JTextField txtIDWiz;
    private javax.swing.JTextField txtWyszukajWiz;
    // End of variables declaration//GEN-END:variables
}
